zuul:
  routes:
    service-a:
      path: /first/**
      serviceId: 111
      url: http://localhost:8181  #수동등록
    service-b:
      path: /second/**
      serviceId: 222
      url: http://localhost:8182  #수동등록

hystrix:
  command:
    service-b:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

service-a:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100