spring:
  application:
    name: zuul

server:
  port: 8765

zuul:
  routes:
    service-a:
      path: /first/**
      serviceId: 111
      stripPrefix: false
      url: http://localhost:8181  #수동등록
    service-b:
      path: /second/**
      serviceId: 222
      stripPrefix: false
      url: http://localhost:8182  #수동등록
#  ratelimit:
#    enabled: true
#    repository: JPA
#    policy-list:
#      service-a:
#        - limit: 5
#          refresh-interval: 60
#          type:
#            - origin
#      service-b:
#        - limit: 1
#          refresh-interval: 2
#          type:
#            - origin
#  strip-prefix: true



eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetchRegistry: true
    registry-sync-retries: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#service-a:
#  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    ConnectTimeout: 1000
#    ReadTimeout: 3000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100