server:
  port: 8181

spring:
  application:
    name: service-a

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # default address
    register-with-eureka: true
    fetchRegistry: true
    registry-sync-retries: 5

